;Wap to multiply two 8 bits number stored at locations 70H and 71H and store the result at memory locations 52H and 53H .assume that the LSB of the result is stored in low address.
ORG 0000H;SET PROGRAM COUNTER 00 0H
MOV A,70H;LOAD THE CONTENTS OF MEMORY LOCATION 70H INTO A
MOV B,71H;LOAD THE CONTENTS OF MEMORY LOCATION 71H INTO B
MUL AB;PERFORM MULTIPLICATION
MOV 52H,A;SAVE THE LEAST SIGNIFICANT BYTE OF THE RESULT IN LOCATION 52H
MOV 53H,B;SAVE THE LEAST SIGNIFICANT BYTE OF THE RESULT IN LOCATION 53H
END

